# Basic
name:               "Aaron Connolly"
description:        "Christ Follower, Husband, Father, Software Engineer, Taco Lover"

url:                "https://www.aaronconnolly.com"
author:             "chefnobody"
twitter:
  username:         "chefnobody"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "about/"
  - name:           "Github"
    href:           "http://github.com/chefnobody"
  - name:           "Reading List"
    href:           "reading-list/"
  - name:           "Resume"
    href:           "assets/mac-resume-5-28-2020.pdf"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
